export const ERROR = 'ERROR'

// Message specific action names
export const MESSAGES_ADD = 'MESSAGES_ADD'
export const MESSAGES_INSERT = 'MESSAGES_INSERT'
export const MESSAGES_DELETE = 'MESSAGES_DELETE'
export const MESSAGES_EDIT = 'MESSAGES_EDIT'
export const MESSAGES_UPDATE = 'MESSAGES_UPDATE'
export const MESSAGES_COMPLETE = 'MESSAGES_COMPLETE'

export const COMPLETE_ALL = 'COMPLETE_ALL'
export const CLEAR_COMPLETED = 'CLEAR_COMPLETED'
export const SET_SYNC_STATE = 'SET_SYNC_STATE';
